import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Saurabh Sahani | Portfolio",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta charSet="UTF-8" />
   
      <body className={inter.className}>
        <main className="w-screen h-screen overflow-x-hidden lg:overflow-y-hidden bg-gradient-to-b from-blue-50 to-red-100">
          <div className="sm:h-24 h-16">
          <Navbar/>
          </div>
          <div className="h-[calc(100vh-6rem)]">
            {children}
          </div>
        </main>
        </body>
    </html>
  );
}
